version: "3"
services:
  opendevin_frontend:
    container_name: opendevin_frontend
    image: "opendevin/frontend"
    ports:
      - "3001:3001"
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - opendevin_server
  opendevin_server:
    container_name: opendevin_server
    image: "opendevin/server"
    ports:
      - "3000:3000"
    networks:
      - default

